config/routes.rb
Myvideos::Application.routes.draw do
  resources :videos

  resources :video_categories

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/newalbum', to: 'video_categories#new'    
  
  match '/newvideo', to: 'videos#new'

  get "home/index"
  root :to => 'home#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  
  has_many :video_categories, dependent: :destroy
  has_many :videos, :through => :video_categories 

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, :only => [:show]
  
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
    @videos = @user.videos        
    @album_videos = @user.video_categories.find_by_id(params[:cat_id]).videos unless params[:cat_id].nil? 
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the My Videos!"
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  private
  def signed_in_user    
    store_location
    if !signed_in? || User.find(params[:id]) != current_user
        redirect_to root_url, notice: "Invalid URL"
    end        
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %><br />

  <%= f.submit "Create my account", class: "btn btn-primary" %>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h4>Sign up</h4>
<div class="row">	
	<div class="span9 offset3">
		<%= render 'users/form'%>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span3">
    <section>
      <h4>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h4>
      <div class="row">
      	<div class="span3">
      		<h5>Albums</h5>
      	</div>
      	<%= render(@user.video_categories)%>
      </div>
      <h6><%= link_to "New Album", newalbum_path %></h6>
    </section>
  </aside>
  <div class="span9">
  	<% if @album_videos.nil?%>
  		<%= render(@videos)%>
  	<% else %>
  		<%= render(@album_videos)%>
  	<% end %>
  	<h6><%= link_to "New Video", newvideo_path%></h6>
  </div>
</div>