config/routes.rb
Myvideos::Application.routes.draw do
  resources :videos

  resources :video_categories

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/newalbum', to: 'video_categories#new'    
  
  match '/newvideo', to: 'videos#new'

  get "home/index"
  root :to => 'home#index'

end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :video_category_id, :title, :url
  
  belongs_to :video_category
  
  VALID_URL_REGEX = /^https?:\/\/(?:[0-9A-Z-]+\.)?(?:youtu\.be\/|youtube\.com\S*[^\w\-\s])([\w\-]{11})(?=[^\w\-]|$)(?![?=&+%\w]*(?:['"][^<>]*>|<\/a>))[?=&+%\w-]*/ix
  
  validates :video_category_id, presence: true
  validates :title, presence: true, length: {maximum: 50}, uniqueness: true
  validates :url, presence: true, length: {maximum: 50}, format: { with: VALID_URL_REGEX } 
    
  
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController  
  before_filter :signed_in_user
  
  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    if current_user.video_categories.count ==0 
      redirect_to newalbum_url, notice: 'There is no album, please first create an album.'
      return
    end
    
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(params[:video])

    respond_to do |format|
      if @video.save
        format.html { redirect_to root_url, notice: 'Video has been successfully created.' }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action: "new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Video was successfully deleted.' }
      format.json { head :no_content }
    end
  end
  
  private
  def signed_in_user
    if params[:action] == 'index' || params[:action] == 'show'
      redirect_to root_url, notice: "Invalid URL"
      return
    end
    store_location
    redirect_to root_url, notice: "Please sign in." unless signed_in?
  end
  
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<div class="row">
  <%= render 'layouts/leftside' %>
  <div class="span9">
  	<h3>New Video</h3>
	<%= form_for(@video) do |f| %>
		<%= render 'shared/error_messages_video' %>
		
	  	<%= f.label :video_category_id, "Album" %>
	    <%= f.collection_select(:video_category_id, current_user.video_categories.all, :id, :category, :include_blank => "Please select...") %> <br />
	    
	    <%= f.label :title, "Video Title" %>
	    <%= f.text_field :title %> <br />
	    
	    <%= f.label :url, "Video URL - only youtube" %>
	    <%= f.text_field :url %> <br />
	    
      	<%= f.submit "Add Video", class: "btn btn-primary" %>
      	
	<% end %>
  </div>
</div>

app/views/videos/_video.html.erb
<%#=  debug("hello world") 
%>
<% #Rails.logger.debug("hello world") 
%>
<div class="row">	
<div class="span12"><%= video.title%>&nbsp;&nbsp;&nbsp;&nbsp;
	<% if signed_in? %>
	<%= link_to "Delete", video, :method => :delete, :confirm => 'Are you sure you want to delete this video?'%>
	<% end %>
</div>
<div class="span12"><%= youtube_video video.url %></div>
</div>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<h1>Listing videos</h1>

<table>
  <tr>
    <th>Category</th>
    <th>Title</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @videos.each do |video| %>
  <tr>
    <td><%= video.video_category_id %></td>
    <td><%= video.title %></td>
    <td><%= video.url %></td>
    <td><%= link_to 'Show', video %></td>
    <td><%= link_to 'Edit', edit_video_path(video) %></td>
    <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<%= render 'form' %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Category:</b>
  <%= @video.video_category_id %>
</p>

<p>
  <b>Title:</b>
  <%= @video.title %>
</p>

<p>
  <b>Url:</b>
  <%= @video.url %>
</p>


<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>