config/routes.rb
Myvideos::Application.routes.draw do
  resources :videos

  resources :video_categories

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/newalbum', to: 'video_categories#new'    
  
  match '/newvideo', to: 'videos#new'

  get "home/index"
  root :to => 'home#index'

end

app/models/video_category.rb
class VideoCategory < ActiveRecord::Base
  attr_accessible :category
  
  has_many :videos, dependent: :destroy
    
  belongs_to :user
  
  validates :user_id, presence: true
  validates :category, presence: true, length: {maximum: 30}, uniqueness: {:scope => :user_id}
  
end

app/controllers/video_categories_controller.rb
class VideoCategoriesController < ApplicationController
  before_filter :signed_in_user
  
  
  
  # GET /video_categories
  # GET /video_categories.json
  def index
    @video_categories = VideoCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @video_categories }
    end
  end

  # GET /video_categories/1
  # GET /video_categories/1.json
  def show
    @video_category = VideoCategory.find(params[:id])
    @videos = @video_category.videos 
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video_category }
    end
  end

  # GET /video_categories/new
  # GET /video_categories/new.json
  def new
    @video_category = VideoCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video_category }
    end
  end

  # GET /video_categories/1/edit
  def edit
    @video_category = VideoCategory.find(params[:id])
  end

  # POST /video_categories
  # POST /video_categories.json
  def create
    @video_category = current_user.video_categories.build(params[:video_category])
    logger.info @video_category.category
    respond_to do |format|
      if @video_category.save
        format.html { redirect_to root_url, notice: 'Album has been successfully created.' }
        format.json { render json: @video_category, status: :created, location: @video_category }
      else
        format.html { render action: "new" }
        format.json { render json: @video_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /video_categories/1
  # PUT /video_categories/1.json
  def update
    @video_category = VideoCategory.find(params[:id])

    respond_to do |format|
      if @video_category.update_attributes(params[:video_category])
        format.html { redirect_to @video_category, notice: 'Video category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /video_categories/1
  # DELETE /video_categories/1.json
  def destroy
    @video_category = VideoCategory.find(params[:id])
    @video_category.destroy

    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Album was successfully deleted.' }
      format.json { head :no_content }
    end
  end
  
  private
  def signed_in_user
    if params[:action] == 'index' || params[:action] == 'show'
      redirect_to root_url, notice: "Invalid URL"
      return
    end
    store_location
    redirect_to root_url, notice: "Please sign in." unless signed_in?
  end
  
end

app/helpers/video_categories_helper.rb
module VideoCategoriesHelper
end

app/views/video_categories/_form.html.erb
<div class="row">
  <%= render 'layouts/leftside' %>
  <div class="span9">
	<%= form_for(@video_category) do |f| %>
		<%= render 'shared/error_messages_category' %>
		
	  	<%= f.label :category, "Album Name" %>
	    <%= f.text_field :category %> <br />
	    
      	<%= f.submit "Create Album", class: "btn btn-primary" %>
      	
	<% end %>
  </div>  
</div>

app/views/video_categories/_video_category.html.erb

<div class="span3">
	<%= link_to video_category.category, {:controller => "home", :action => "index", :id => current_user.id, :cat_id => video_category.id } %>
	<%= link_to "Delete Album", video_category, :method => :delete, :confirm => "This will delete all videos in this album, are you sure?"%>
</div>

app/views/video_categories/edit.html.erb
<h1>Editing video_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @video_category %> |
<%= link_to 'Back', video_categories_path %>

app/views/video_categories/index.html.erb
<h1>Listing video_categories</h1>

<table>
  <tr>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @video_categories.each do |video_category| %>
  <tr>
    <td><%= video_category.category %></td>
    <td><%= link_to 'Show', video_category %></td>
    <td><%= link_to 'Edit', edit_video_category_path(video_category) %></td>
    <td><%= link_to 'Destroy', video_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Video category', new_video_category_path %>

app/views/video_categories/new.html.erb
<%= render 'form' %>

app/views/video_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Category:</b>
  <%= @video_category.category %>
</p>


<%= link_to 'Edit', edit_video_category_path(@video_category) %> |
<%= link_to 'Back', video_categories_path %>