config/routes.rb
Myvideos::Application.routes.draw do
  resources :videos

  resources :video_categories

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/newalbum', to: 'video_categories#new'    
  
  match '/newvideo', to: 'videos#new'

  get "home/index"
  root :to => 'home#index'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
<p align="center">Sample application in process to learn Rails - Numan Ilyas </p>  
</footer>

app/views/layouts/_leftside.html.erb
<aside class="span3">
	    <section>
	    	<% if signed_in? %>
		      <h4>
		        <%= gravatar_for current_user %>
		        <%= current_user.name %>
		      </h4>
		      <div class="row">
		      	<div class="span3">
		      		<h5>Albums</h5>
		      		<% if current_user.video_categories.count == 0 %>
		      			<p>There are no albums, please create.</p>
		      		<% end %>
		      	</div>
		      	
		      	<%= render(current_user.video_categories)%>
		      </div>
		      <h6><%= link_to "New Album", newalbum_path %></h6>
		    <% else %>
		    	<h4>Sign Up</h4>
				<%= render 'users/form'%>    
		    <% end %>	      
	    </section>
    </aside>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_topnavigation.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "My Videos", root_path, class: "brand" %>
      <nav class="nav pull-right">
        <ul class="nav pull-right">
          <% if signed_in? %>
          	<li>
          	<%= link_to "Sign out", signout_path, method: "delete" %>
          	</li>
            <!-- li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li -->
          <% else %>
            <%= render 'sessions/header_signin'%>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "My Videos" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/topnavigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>